project:
  type: website
website:
  title: |
    ![](logo.png){width=50px .nolightbox} &nbsp; Website title here
  site-url: ""
  description: "Website description here."
  navbar:
    right:
      - icon: file-text
        text: Resume/CV
        href: CV.qmd
      - icon: bar-chart
        text: Data viz
        href: data-portfolio.qmd
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com
  google-analytics: ""
  cookie-consent:
    type: implied
    style: simple
  favicon: favicon.png
  twitter-card:
    creator: "@"
  open-graph: true
  page-footer:
    left: "Blog template made with 💖 and [Quarto](https://quarto.org/), by Rebecca Senft <br>License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    center: "[Blog {{< fa brands github >}} repo](https://github.com/rsenft1/quarto-website-template)"
    right:
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com

format:
  html:
    theme:
      light: [united, custom.scss]
    css: styles.css

editor: visual
